# Generated by Django 4.1.13 on 2024-09-26 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerRegistrationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50, unique=True)),
                ('MobileNumber', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Owner_registration_collection',
            },
        ),
    ]
