# Generated by Django 4.1.13 on 2024-09-26 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RestaurentName', models.CharField(max_length=100)),
                ('Type', models.CharField(max_length=50)),
                ('RegistrationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OwnerID', to='restaurant_app.ownerregistrationmodel')),
            ],
            options={
                'db_table': 'restaurent_collection',
            },
        ),
    ]
