# Generated by Django 4.1.13 on 2024-09-26 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0002_restaurentmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomurRegistrationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomurName', models.CharField(max_length=50)),
                ('CustomurEmail', models.EmailField(max_length=50, unique=True)),
                ('CustomurMobileNumber', models.CharField(max_length=50)),
                ('CustomurPassword', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Customur_registration_collection',
            },
        ),
    ]
