# Generated by Django 4.1.13 on 2024-09-26 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0003_customurregistrationmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemName', models.CharField(max_length=500)),
                ('Price', models.CharField(max_length=50)),
                ('Available', models.CharField(max_length=50)),
                ('RestaurentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurent_item', to='restaurant_app.restaurentmodel')),
            ],
            options={
                'db_table': 'items_collection',
            },
        ),
    ]
