# Generated by Django 4.1.13 on 2024-09-26 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0004_itemmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemsModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.CharField(max_length=50)),
                ('SpecialInstruction', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('update_on', models.DateTimeField(auto_now=True)),
                ('CustomurID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item', to='restaurant_app.customurregistrationmodel')),
                ('itemID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item', to='restaurant_app.itemmodel')),
            ],
            options={
                'db_table': 'orders_collection',
            },
        ),
    ]
